# Nushell PATH — hand-maintained mirror of shellPath (.chezmoidata.yaml).
# See shell/env.sh.tmpl (bash/zsh) and fish/conf.d/00-env.fish.tmpl.

# Inside env.nu, $env.PATH is still a string — nushell converts it to a list
# only after env.nu and config.nu are read. Split it once so the edits below
# operate on a proper list.
$env.PATH = ($env.PATH | split row (char esep))

# Homebrew (macOS only) — prepended for priority
if $nu.os-info.name == "macos" {
    $env.PATH = ($env.PATH | prepend ["/opt/homebrew/bin" "/opt/homebrew/sbin" "/opt/homebrew/opt/openjdk/bin"])
}

# pyenv — nushell is the login shell, so .zshrc never runs; add bin + shims ourselves
$env.PYENV_ROOT = ($env.HOME | path join ".pyenv")
let pyenv_bin = ($env.PYENV_ROOT | path join "bin")
if ($pyenv_bin | path exists) {
    $env.PATH = ($env.PATH | prepend $pyenv_bin)
}
let pyenv_shims = ($env.PYENV_ROOT | path join "shims")
if ($pyenv_shims | path exists) {
    $env.PATH = ($env.PATH | prepend $pyenv_shims)
}

# opencode
let opencode_bin = ($env.HOME | path join ".opencode" "bin")
if ($opencode_bin | path exists) {
    $env.PATH = ($env.PATH | append $opencode_bin)
}

# chezmoi
let local_bin = ($env.HOME | path join ".local" "bin")
if ($local_bin | path exists) {
    $env.PATH = ($env.PATH | append $local_bin)
}

# env.nu runs once per nested shell; dedup so PATH doesn't accumulate
$env.PATH = ($env.PATH | uniq)

# starship — init.nu is generated by run_once_after_starship so it exists
# before nushell parses this file. Regenerate after starship updates:
#   starship init nu | save -f ~/.cache/starship/init.nu
use ~/.cache/starship/init.nu