---
- name: Check Homebrew (Apple Silicon)
  ansible.builtin.stat:
    path: /opt/homebrew/bin/brew
  register: brew_arm
  when: os_var_file == 'macos'

- name: Check Homebrew (Intel)
  ansible.builtin.stat:
    path: /usr/local/bin/brew
  register: brew_x86
  when: os_var_file == 'macos'

- name: Bootstrap Homebrew
  ansible.builtin.shell:
    cmd: NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  args:
    warn: false
  when:
    - os_var_file == 'macos'
    - not brew_arm.stat.exists
    - not brew_x86.stat.exists

- name: Install CLI packages (Manjaro)
  community.general.pacman:
    name: "{{ cli_packages }}"
    state: present
  become: true
  when: os_var_file == 'manjaro'

- name: Install development tools group (Fedora)
  ansible.builtin.dnf:
    name: "{{ development_group }}"
    state: present
  become: true
  when: os_var_file == 'fedora'

- name: Install CLI packages (Fedora)
  ansible.builtin.dnf:
    name: "{{ cli_packages }}"
    state: present
  become: true
  when: os_var_file == 'fedora'

- name: Install CLI packages (macOS)
  community.general.homebrew:
    name: "{{ brew_formulae }}"
    state: present
  when: os_var_file == 'macos'

- name: Check pyenv directory
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.pyenv"
  register: pyenv_dir
  when: os_var_file in ['manjaro', 'fedora']

- name: Check pyenv git repo
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.pyenv/.git"
  register: pyenv_git
  when: os_var_file in ['manjaro', 'fedora']

- name: Install pyenv
  ansible.builtin.git:
    repo: https://github.com/pyenv/pyenv.git
    dest: "{{ ansible_env.HOME }}/.pyenv"
    version: master
  when:
    - os_var_file in ['manjaro', 'fedora']
    - not pyenv_dir.stat.exists or pyenv_git.stat.exists

- name: Install pyenv-virtualenv
  ansible.builtin.git:
    repo: https://github.com/pyenv/pyenv-virtualenv.git
    dest: "{{ ansible_env.HOME }}/.pyenv/plugins/pyenv-virtualenv"
    version: master
  when:
    - os_var_file in ['manjaro', 'fedora']
    - not pyenv_dir.stat.exists or pyenv_git.stat.exists
