wallpaper {
    monitor = DP-2
    path = /home/hegdesrinivasm/Pictures/Wallpapers/wallhaven-o525z9.jpg
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/hegdesrinivasm/Pictures/Wallpapers/wallhaven-o525z9.jpg
}
