---
all:
  children:
    windows:
      hosts:
        win.local:
      vars:
        ansible_connection: ssh
        ansible_user: hegdesrinivasm
        ansible_shell_type: powershell
        ansible_ssh_common_args: "-o StrictHostKeyChecking=accept-new"
