---
- name: Converge machine to desired state
  hosts: all
  gather_facts: true
  become: false
  pre_tasks:
    - name: Determine platform
      ansible.builtin.set_fact:
        os_var_file: >-
          {{ 'windows' if ansible_facts['os_family'] == 'Windows'
             else 'manjaro' if ansible_facts['distribution'] in ['Manjaro', 'Archlinux']
             else 'fedora' if ansible_facts['distribution'] == 'Fedora'
             else 'macos' if ansible_facts['os_family'] == 'Darwin'
             else 'unsupported' }}
    - name: Load per-OS variables
      ansible.builtin.include_vars:
        file: "{{ playbook_dir }}/../inventories/group_vars/{{ os_var_file }}.yml"
  roles:
    - common
    - apps
    - dotfiles
    - shell
