---
os_var_file: fedora
development_group: "@development-tools"
cli_packages:
  - nodejs
  - java-latest-openjdk
  - golang
  - lua
  - nushell
  - neovim
  - fish
  - git
  - curl
  - tailscale
  - uv
  - bzip2
  - zoxide
  - fzf
  - starship
flatpak_apps:
  - com.bitwarden.desktop
  - io.ente.auth
