---
os_var_file: manjaro
cli_packages:
  - nodejs
  - npm
  - jdk-openjdk
  - go
  - lua
  - nushell
  - ghostty
  - neovim
  - fish
  - git
  - curl
  - base-devel
  - github-cli
  - ollama
  - tailscale
  - zoxide
  - fzf
flatpak_apps:
  - com.bitwarden.desktop
  - io.ente.auth
aur_packages:
  - visual-studio-code-bin
hypr_packages:
  - hyprland
  - waybar
  - hyprpaper
  - wofi
  - network-manager-applet
  - gnome-control-center
  - xdg-desktop-portal-hyprland
