"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
palette = "spiderman"

format = """
$directory\
$git_branch\
$git_status\
$python\
$nodejs\
$ruby\
$java\
$docker_context
$character"""

right_format = "$cmd_duration$time"

[palettes.spiderman]
fg = "#e3e3e3"
bright = "#fffef6"
gray = "#505354"
red = "#e60813"
bright_red = "#ff0325"
light_red = "#e24756"
blue = "#2c3fff"
blue_2 = "#1d50ff"
light_blue = "#6184ff"
mid_blue = "#747cff"

[package]
disabled = true

[directory]
truncation_length = 3
truncation_symbol = ".../"
read_only = " readonly"
read_only_style = "gray"
format = "[$path]($style)[$read_only]($read_only_style) "
style = "blue"

[git_branch]
symbol = ""
format = "[on $symbol$branch]($style) "
style = "light_blue"

[git_status]
format = "([\\[$all_status$ahead_behind\\]]($style) )"
style = "red"
conflicted = "≈"
ahead = "⇡"
behind = "⇣"
diverged = "⇕"
untracked = "?"
staged = "+"
modified = "~"
renamed = "»"
deleted = "✘"

[python]
format = "[$symbol$version]($style) "
symbol = ""
style = "red"

[nodejs]
format = "[$symbol$version]($style) "
symbol = ""
style = "blue"

[ruby]
format = "[$symbol$version]($style) "
symbol = ""
style = "blue_2"

[java]
format = "[$symbol$version]($style) "
symbol = ""
style = "light_red"

[docker_context]
format = "via [$symbol$context]($style) "
symbol = ""
style = "gray"

[cmd_duration]
min_time = 2_000
format = "took [$duration](gray) "

[time]
time_format = "%H:%M"
format = "[$time]($style) "
style = "gray"
disabled = false

[character]
success_symbol = "[➜](bold blue)"
error_symbol = "[✗](bold bright_red)"
